use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

const POOL_NAMES: &[&str] = &[
    "landing",
    "asteroid_base",
    "oort_cloud",
    "maximum_space",
    "triggered",
    "system_entry",
    "proximity_star",
    "proximity_base",
    "planet_landing",
    "dyson_landing",
];

fn walk_yaml_files(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries = fs::read_dir(root)
        .map_err(|e| format!("Failed to read directory {}: {}", root.display(), e))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("Failed to read directory entry: {}", e))?;
        let path = entry.path();
        if path.is_dir() {
            walk_yaml_files(&path, files)?;
            continue;
        }
        if path.extension().is_some_and(|ext| ext == "yaml") {
            files.push(path);
        }
    }
    Ok(())
}

fn to_const_name(pool: &str) -> String {
    format!("{}_EVENT_FILES", pool.to_ascii_uppercase())
}

fn main() -> Result<(), String> {
    println!("cargo:rerun-if-changed=content/events");

    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR")
            .map_err(|e| format!("CARGO_MANIFEST_DIR is unavailable: {}", e))?,
    );
    let events_root = manifest_dir.join("content").join("events");

    let mut discovered = Vec::new();
    walk_yaml_files(&events_root, &mut discovered)?;
    discovered.sort();

    let mut by_pool: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for pool in POOL_NAMES {
        by_pool.insert((*pool).to_string(), Vec::new());
    }

    for path in discovered {
        let rel = path
            .strip_prefix(&events_root)
            .map_err(|e| format!("Failed to strip events root prefix: {}", e))?;
        let rel_string = rel.to_string_lossy().replace('\\', "/");
        let pool = rel
            .components()
            .next()
            .ok_or_else(|| format!("Invalid event path {}", rel_string))?
            .as_os_str()
            .to_string_lossy()
            .to_string();
        let files = by_pool
            .get_mut(&pool)
            .ok_or_else(|| format!("Unknown event pool '{}' for file '{}'", pool, rel_string))?;
        files.push(rel_string);
    }

    let out_dir = PathBuf::from(
        env::var("OUT_DIR").map_err(|e| format!("OUT_DIR is unavailable: {}", e))?,
    );
    let out_path = out_dir.join("generated_event_registry.rs");
    let mut file = fs::File::create(&out_path)
        .map_err(|e| format!("Failed to create {}: {}", out_path.display(), e))?;

    writeln!(file, "// @generated by build.rs; do not edit.")
        .map_err(|e| format!("Failed writing generated file header: {}", e))?;
    writeln!(file, "pub const TOTAL_EVENT_FILE_COUNT: usize = {};",
        by_pool.values().map(|v| v.len()).sum::<usize>()
    ).map_err(|e| format!("Failed writing TOTAL_EVENT_FILE_COUNT: {}", e))?;

    for pool in POOL_NAMES {
        let const_name = to_const_name(pool);
        let files = by_pool
            .get(*pool)
            .ok_or_else(|| format!("Internal error: missing pool {}", pool))?;
        writeln!(
            file,
            "pub const {}: &[(&str, &str)] = &[",
            const_name
        )
        .map_err(|e| format!("Failed writing const {}: {}", const_name, e))?;
        for rel in files {
            writeln!(
                file,
                "    (\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/content/events/{}\"))),",
                rel, rel
            )
            .map_err(|e| format!("Failed writing registry entry {}: {}", rel, e))?;
        }
        writeln!(file, "];").map_err(|e| format!("Failed closing const {}: {}", const_name, e))?;
    }

    Ok(())
}
